### ISSUE TITLE
Failure to parse units

### ISSUE THREAD

**Issue by boada** [stvnksslr/dataslate-parser#25]
> In [2]: from app.parsers.heresy.heresy import parse_units 
> In [7]: f = open('test.ros')                                                                                                         
> 
> In [8]: parse_units(f)                                                                                                                           
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-8-c34f8015a0c4> in <module>
> ----> 1 parse_units(f)
> 
> ~/dataslate-parser/app/parsers/heresy/heresy.py in parse_units(roster_file)
>      17         "Solar Aux Superheavy",
>      18     ]
> ---> 19     parsed_list = data_cleanse(rule_whitelist, soup)
>      20     return parsed_list
>      21 
> 
> ~/dataslate-parser/app/parsers/heresy/heresy.py in data_cleanse(rule_whitelist, soup)
>      25     filter_out_non_unit_entries(rule_whitelist, selections)
>      26     list_of_squads = get_squads(selections)
> ---> 27     parsed_list = create_parsed_list(list_of_squads)
>      28     return parsed_list
>      29 
> 
> ~/dataslate-parser/app/parsers/heresy/heresy.py in create_parsed_list(list_of_squads)
>      36         parsed_list.append(
>      37             UnitGroup(
> ---> 38                 name=squads[0].get("unit_name"),
>      39                 list_of_units=parsed_squads,
>      40                 toughness=toughness,
> 
> IndexError: list index out of range
> 

Battlescribe 2.03.12

I had to rename the roster extension to '.txt' so I could attach it to this issue. 

[test.ros.txt](https://github.com/stvnksslr/dataslate-parser/files/5079034/test.ros.txt)

**Comment by stvnksslr** [comment]
Battlescribe was doing a big update push fairly recently, let me take a look and see what new and exciting thing has broken. 

Thank you for the bug reports!

**Comment by stvnksslr** [comment]
```
    rule_whitelist = [
        "Rite of War",
        "Legion and Allegiance",
        "Use Playtest Rules",
        "Allegiance",
        "Legio",
        "Mournival Rules",
        "Solar Aux Superheavy",
->    "Use Playtest Rules Errata 1.0 (From FAQ 1.1 Feb/2019)"
    ]
```
They changed the text for the playtest rules so it wasnt being excluded, ive committed the fixes
