### ISSUE TITLE
Poetry Fails Install

### ISSUE THREAD

**Issue by boada** [stvnksslr/dataslate-parser#26]
On ubuntu after installing `poetry` with `pip` the `poetry install` failed for me. [See this issue](https://github.com/python-poetry/poetry/issues/2711). The fix is at the bottom of the page. 

`pip install --user --pre poetry -U`

Seems `poetry` will fix this at some point, but for other that have a similar issue, this resolved it for me.

Maybe update the documentation?

**Comment by stvnksslr** [comment]
Ah super weird Ive not run into that issue before normally install poetry via pipx. 

I will include an up to date req.txt so the project can be installed with normal pip easily.
