### ISSUE TITLE
App Fails to Run Out of the Box

### ISSUE THREAD

**Issue by boada** [stvnksslr/dataslate-parser#27]
After cloning the repo, and getting the dependencies installed with `poetry` I was not able to immediately run the app. 

Running `uvicorn main:app` in the top level results in 

> $ uvicorn main:app
> ERROR:    Error loading ASGI app. Could not import module "main".

Running it in the `app` directory gives:

> ModuleNotFoundError: No module named 'app'

I suppose this has to do with the imports looking for the `app` folder, which I was in... This issue is solved by moving `main.py` to the top level and then issuing `uvicorn main:app`

**Comment by stvnksslr** [comment]
`uvicorn app.main:app`

will fix that pathing issue, I apologize for the documentation being out of date will get it fixed up.
