### ISSUE TITLE
Questions about evolutions around W40k

### ISSUE THREAD

**Issue by jermarchand** [stvnksslr/dataslate-parser#35]
Hi,

The evolutions that I would like to add to the support of w40K:

- add an "army list" part in ETC format, with a checkbox on the import page => Is it applicable to other formats (KillTeam, Heresy) ?
- add the "army's rules" => but that would require modifying the way of parsing in the `main.py` because it is Heresy's which is used at this level.
- add logos in the column headers => like https://imgur.com/a/uPJukOy
- add support of "declining profile" => I don't test it
- ...

**Comment by stvnksslr** [comment]
If you have a sample for the ETC list format id be happy to help on that one shouldn't be too hard.

ill fix the army rules bit that's just some laziness on my part

add logos in the column headers shouldn't be too bad to match that format.

what do you mean by declining profile?

**Comment by stvnksslr** [comment]
ah ok that makes sense, thank you for your work on the project! 

I really appreciate it.
